import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import "./globals.css";
import { ToastProvider } from "./context/ToastContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray-900 text-white min-h-screen`}>
        <ToastProvider>
          <header>
            <Navbar />
          </header>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
